# Generated by Django 3.0.3 on 2020-02-22 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IndigenousPeople', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField()),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IndigenousPeople.CultureInfo')),
            ],
        ),
    ]
