# Generated by Django 3.0.3 on 2020-02-22 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IndigenousPeople', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='cultureinfo',
            old_name='culture_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
