# Generated by Django 3.0.3 on 2020-02-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndigenousPeople', '0005_auto_20200222_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='product1',
            name='price',
            field=models.IntegerField(default=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product2',
            name='price',
            field=models.IntegerField(default=420),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product3',
            name='price',
            field=models.IntegerField(default=6969),
            preserve_default=False,
        ),
    ]
